server:
  address: 0.0.0.0
  port: 7560

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eagle
    username: root
    password: xx@33
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  type-enums-package: com.autotest.eagle.enums


# 日志配置
logging:
  file.max-history: 7
  file.max-size: 1024MB
  level:
    root: info
    org.apache.kafka: error
    com.autotest.eagle.mapper: info
  file:
    name: logs/common-logback.log